### ISSUE TITLE
Dodanie komentarza pod postem

### ISSUE THREAD

**Issue by geodotka** [pawelkowalik/blog#2]

**Comment by pawelkowalik** [comment]
już nie czaje co to te issuy i czym sie różnią od commitów, wszystko będziesz mi musiała jutro wytłumaczyć. Próbowałem na cygwinie działać, ale słabo współpracuje z windowsem  10, więc poczekam do jutra na linuksa

**Comment by geodotka** [comment]
Boję się tylko, żeby Ci tego windowsa nie popsuć. Bo czasem (dość często) znika windows przy takim instalowaniu.
https://windows.github.com/
Ale nie działa z 10.
